#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright © 2021 n <nicolas.trutmann@gmx.ch>
#
# Distributed under terms of the MIT license.

"""
replace some lines in a text delimited by marker
"""

import os
import argparse

DELIM = '!!!! Color scheme'
file = os.path.expanduser('~/.Xresources')

cs_vscode_dark = """
!! name: VSCode Dark,
.*foreground: #CCCCCC
.*background: #1E1E1E
.*cursorColor: #888888
.*color0: #000000
.*color1: #cd3131
.*color2: #0DBC79
.*color3: #e5e510
.*color4: #2472c8
.*color5: #bc3fbc
.*color6: #11a8cd
.*color7: #e5e5e5
.*color8:  #666666
.*color9:  #f14c4c
.*color10: #23d18b
.*color11: #f5f543
.*color12: #3b8eea
.*color13: #d670d6
.*color14: #29b8db
.*color15: #e5e5e5

"""

cs_solarized = """
!! solarized

! special
*.foreground:   #93a1a1
*.background:   #002b36
*.cursorColor:  #93a1a1

! black
*.color0:       #002b36
*.color8:       #657b83

! red
*.color1:       #dc322f
*.color9:       #dc322f

! green
*.color2:       #859900
*.color10:      #859900

! yellow
*.color3:       #b58900
*.color11:      #b58900

! blue
*.color4:       #268bd2
*.color12:      #268bd2

! magenta
*.color5:       #6c71c4
*.color13:      #6c71c4

! cyan
*.color6:       #2aa198
*.color14:      #2aa198

! white
*.color7:       #93a1a1
*.color15:      #fdf6e3
"""

cs_gotham = """
!!    scheme: gotham

*.foreground:   #98d1ce
*.background:   #0a0f14
*.cursorColor:  #98d1ce

! black
*.color0:       #0a0f14
*.color8:       #10151b

! red
*.color1:       #c33027
*.color9:       #d26939

! green
*.color2:       #26a98b
*.color10:      #081f2d

! yellow
*.color3:       #edb54b
*.color11:      #245361

! blue
*.color4:       #195465
*.color12:      #093748

! magenta
*.color5:       #4e5165
*.color13:      #888ba5

! cyan
*.color6:       #33859d
*.color14:      #599caa

! white
*.color7:       #98d1ce
*.color15:      #d3ebe9
"""

cs_unknown = """
! special
*.foreground:   #888888
*.background:   #151515
*.cursorColor:  #888888

! black
*.color0:       #292929
*.color8:       #525252

! red
*.color1:       #cf6a4c
*.color9:       #ff9d80

! green
*.color2:       #19cb00
*.color10:      #23fd00

! yellow
*.color3:       #fad07a
*.color11:      #ffefbf

! blue
*.color4:       #8197bf
*.color12:      #accaff

! magenta
*.color5:       #8787af
*.color13:      #c4c4ff

! cyan
*.color6:       #668799
*.color14:      #80bfaf

! white
*.color7:       #888888
*.color15:      #e8e8d3
"""

cs_tartan = """
!! tartan
! special
*.foreground:   #dedede
*.background:   #2b2b2b
*.cursorColor:  #dedede

! black
*.color0:       #2e3436
*.color8:       #555753

! red
*.color1:       #cc0000
*.color9:       #ef2929

! green
*.color2:       #4e9a06
*.color10:      #8ae234

! yellow
*.color3:       #c4a000
*.color11:      #fce94f

! blue
*.color4:       #3465a4
*.color12:      #729fcf

! magenta
*.color5:       #75507b
*.color13:      #ad7fa8

! cyan
*.color6:       #06989a
*.color14:      #34e2e2

! white
*.color7:       #d3d7cf
*.color15:      #eeeeec

"""

cs_kasugano = """
!! kasugano
! special
*.foreground:   #ffffff
*.background:   #1b1b1b
*.cursorColor:  #ffffff

! black
*.color0:       #3d3d3d
*.color8:       #4d4d4d

! red
*.color1:       #6673bf
*.color9:       #899aff

! green
*.color2:       #3ea290
*.color10:      #52ad91

! yellow
*.color3:       #b0ead9
*.color11:      #98c9bb

! blue
*.color4:       #31658c
*.color12:      #477ab3

! magenta
*.color5:       #596196
*.color13:      #7882bf

! cyan
*.color6:       #8292b2
*.color14:      #95a7cc

! white
*.color7:       #c8cacc
*.color15:      #edeff2

"""


cs_kasugano_light = """
!! kasugano light
! special
*.foreground:   #ffffff
*.background:   #444444
*.cursorColor:  #ffffff

! black
*.color0:       #3d3d3d
*.color8:       #4d4d4d

! red
*.color1:       #6673bf
*.color9:       #899aff

! green
*.color2:       #3ea290
*.color10:      #52ad91

! yellow
*.color3:       #b0ead9
*.color11:      #98c9bb

! blue
*.color4:       #31658c
*.color12:      #477ab3

! magenta
*.color5:       #596196
*.color13:      #7882bf

! cyan
*.color6:       #8292b2
*.color14:      #95a7cc

! white
*.color7:       #c8cacc
*.color15:      #edeff2

"""

cs_monokai_d = """
!! monokai
! special
*.foreground:   #f8f8f2
*.background:   #272822
*.cursorColor:  #f8f8f2

! black
*.color0:       #272822
*.color8:       #75715e

! red
*.color1:       #f92672
*.color9:       #f92672

! green
*.color2:       #a6e22e
*.color10:      #a6e22e

! yellow
*.color3:       #f4bf75
*.color11:      #f4bf75

! blue
*.color4:       #66d9ef
*.color12:      #66d9ef

! magenta
*.color5:       #ae81ff
*.color13:      #ae81ff

! cyan
*.color6:       #a1efe4
*.color14:      #a1efe4

! white
*.color7:       #f8f8f2
*.color15:      #f9f8f5
"""

cs_monokai = """
!! monokai
! special
*.foreground:   #f1ebeb
*.background:   #272822
*.cursorColor:  #f1ebeb

! black
*.color0:       #48483e
*.color8:       #76715e

! red
*.color1:       #dc2566
*.color9:       #fa2772

! green
*.color2:       #8fc029
*.color10:      #a7e22e

! yellow
*.color3:       #d4c96e
*.color11:      #e7db75

! blue
*.color4:       #55bcce
*.color12:      #66d9ee

! magenta
*.color5:       #9358fe
*.color13:      #ae82ff

! cyan
*.color6:       #56b7a5
*.color14:      #66efd5

! white
*.color7:       #acada1
*.color15:      #cfd0c2

"""


color_schemes = {
        "vsdark": cs_vscode_dark,
        "gotham": cs_gotham,
        "unknown": cs_unknown,
        "tartan": cs_tartan,
        "kasugano": cs_kasugano,
        "kasugano_light": cs_kasugano_light,
        "monokai": cs_monokai,
        "monokai_d": cs_monokai_d,
        "solarized": cs_solarized
        }


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Change color scheme in .Xresources.')
    parser.add_argument("scheme", choices=color_schemes.keys())
    args = parser.parse_args()

    with open(file) as f:
        text = f.read()

    new_text = text.split(DELIM)
    new_text[1] = color_schemes[args.scheme]
    assert len(new_text) == 3, \
            "Only one delimited Block allowed in file."

    with open(file, 'w') as f:
        f.write(DELIM.join(new_text))

    os.system('xrdb ~/.Xresources')


