#!/usr/bin/bash

####- git bash-completion
. /usr/share/git/completion/git-completion.bash
. /usr/share/bash-completion/bash_completion

####- xset rate
xset r rate 255 60

####- prompt with git branch modify PS1

####- bash in vi mode
set -o vi
bind -m vi-insert "\C-l":clear-screen

####- optional volume control code

####- aliases
alias ll='ls -alhF'
alias la='ls -A'
# alias ll='ls -CF'
alias sshserv='ssh root@trutmann.xyz'
alias sshgit="ssh -t git@trutmann.xyz 'cd /srv/git; $SHELL -il'"
alias lsrepos="ssh -t git@trutmann.xyz 'ls /srv/git'"
alias gs='git status'
alias glog='git log --all --decorate --oneline --graph'

