#!/usr/bin/bash

####- git bash-completion
. /usr/share/git/completion/git-completion.bash
. /usr/share/bash-completion/bash_completion
. ~/.scripts/lib_ethsync.sh

export PATH=${PATH}:~/.scripts/

####- xset rate
xset r rate 230 60

####- prompt with git branch modify PS1
# from here https://bashrcgenerator.com/
export PS1="\[\033[38;5;6m\]\u\[$(tput sgr0)\]: \[$(tput sgr0)\]\[\033[38;5;14m\]\W\[$(tput sgr0)\] \[$(tput sgr0)\]\[\033[38;5;7m\]\$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/')\[$(tput sgr0)\]\\$ \[$(tput sgr0)\]"

####- bash in vi mode
set -o vi
bind -m vi-insert "\C-l":clear-screen

####- optional volume control code

####- aliases
alias ll='ls -alhF'
alias la='ls -A'
# alias ll='ls -CF'
alias sshserv='ssh root@trutmann.xyz'
alias sshgit="ssh -t git@trutmann.xyz 'cd /srv/git; $SHELL -il'"
alias lsrepos="ssh -t git@trutmann.xyz 'ls /srv/git'"
alias gs='git status'
alias glog='git log --all --decorate --oneline --graph'
alias py='python3.10'
alias bashrc='vim ~/work/dotfiles-deploy/scripts/dotf_bashrc'
alias todo='vim ~/todo.md'
alias eth='cd ~/ethz/mse-00 && vim -p *.md'

export EDITOR=vim
